export declare type TypeString = 'bigint' | 'number' | 'string' | 'boolean' | 'symbol' | 'function' | 'object' | 'undefined';
export declare function typeofOr(type: 'bigint', obj: any): obj is bigint;
export declare function typeofOr(type: 'number', obj: any): obj is number;
export declare function typeofOr(type: 'string', obj: any): obj is string;
export declare function typeofOr(type: 'boolean', obj: any): obj is boolean;
export declare function typeofOr(type: 'symbol', obj: any): obj is symbol;
export declare function typeofOr(type: 'object', obj: any): obj is object;
export declare function typeofOr(type: 'undefined', obj: any): obj is undefined;
export declare function typeofOr(type: 'function', obj: any): obj is Function;
export declare function typeofOr(type: TypeString, obj: any): boolean;
export declare function typeofOr(type: TypeString, obj: any, ...objs: any[]): boolean;
export declare function typeofAnd(type: 'bigint', obj: any): obj is bigint;
export declare function typeofAnd(type: 'number', obj: any): obj is number;
export declare function typeofAnd(type: 'string', obj: any): obj is string;
export declare function typeofAnd(type: 'boolean', obj: any): obj is boolean;
export declare function typeofAnd(type: 'symbol', obj: any): obj is symbol;
export declare function typeofAnd(type: 'object', obj: any): obj is object;
export declare function typeofAnd(type: 'undefined', obj: any): obj is undefined;
export declare function typeofAnd(type: 'function', obj: any): obj is Function;
export declare function typeofAnd(type: TypeString, obj: any): boolean;
export declare function typeofAnd(type: TypeString, obj: any, ...objs: any[]): boolean;
